### ISSUE TITLE
initial feature list

### ISSUE THREAD

**Issue by martinjrobins** [trase-cpp/trase#1]
- [x] `Figure` class #2
- [x] `Axis` class #3 
- [x] `Drawable`  class #5 
- [x] `Plot1D` plot class #4 
- [x] `Legend` class #11
-  ~~`SymPlot1D` plot class~~ #6 
-  ~~`Plot2D` class~~ #7 
-  ~~`SymPlot2D` plot class~~ #8
- [x] `BackendGL` openGL drawing class #9 
- [x] serialisation to SVG #16

**Comment by martinjrobins** [comment]
have initial version of `Figure`, `Axis`, `Drawable` and `BackendGL`

**Comment by martinjrobins** [comment]
this is largely complete now
